FROM apache/airflow:2.8.1

USER root
RUN apt-get update && apt-get install -y git && apt-get clean

USER airflow
RUN pip install dbt-snowflake kafka-python pandas snowflake-connector-python python-dotenv