name: Fintech Pipeline CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dbt-ci:
    name: dbt Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dbt
        run: pip install dbt-snowflake==1.8.*

      - name: Create dbt profiles
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml << EOF
          dbt_project:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: ${SNOWFLAKE_ACCOUNT}
                user: ${SNOWFLAKE_USER}
                password: ${SNOWFLAKE_PASSWORD}
                role: DATA_ENG_ROLE
                warehouse: FINTECH_WH
                database: FINTECH_DEV_DB
                schema: STAGING
                threads: 4
                client_session_keep_alive: false
          EOF

      - name: dbt deps
        working-directory: dbt_project
        run: dbt deps

      - name: dbt compile
        working-directory: dbt_project
        run: dbt compile --profiles-dir ~/.dbt --no-partial-parse

  python-ci:
    name: Python Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install flake8

      - name: Lint ingestion code
        run: |
          flake8 ingestion/ \
            --max-line-length=100 \
            --ignore=E501,W503